name: RonFigueroa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83552
title: Ron Figueroa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#26ccec'
    - '#e4eaeb'
    - '#2c56a1'
    - '#16191c'
    - '#fcaa13'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
