name: RonFigueroa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83552
title: Ron Figueroa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171e24'
    - '#fefefe'
    - '#9c9e9e'
    - '#676868'
    - '#c975a6'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
