name: RonFigueroa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83552
title: Ron Figueroa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00abbd'
    - '#5c2d91'
    - '#ed0080'
    - '#fdb813'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.832666372647509
purpose: []
