name: RonFigueroa
favicon: null
layout_spectrum: 0.24467
typography_spectrum: 0.83552
title: Ron Figueroa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171e24'
    - '#d2d2d2'
    - '#e9e9e9'
    - '#9d9d9d'
    - '#606060'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
