name: RonFigueroa
favicon: null
layout_spectrum: 0.87812
typography_spectrum: 0.83552
title: Ron Figueroa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#152771'
    - '#ffffff'
    - '#c8941a'
    - '#9b6211'
    - '#c7c7c7'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
